name: Pipeline

on: push

env:
  REGISTRY: ${{ secrets.REGISTRY_HOST }}/${{ secrets.REGISTRY_USER }}
  REGISTRY_HOST: ${{ secrets.REGISTRY_HOST }}
  IMAGE_TAG: master-${GITHUB_RUN_NUMBER}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: kartki-api-yarn-${{ hashFiles('yarn.lock') }}

      - name: Docker login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Dev Init
        run: make init-ci

      - name: Push dev cache images
        run: make push-dev-cache

      - name: Lint
        run: make lint

      - name: Test
        run: make api-test

      - name: Dev Down
        run: make docker-down-clear

      - name: Inject branch slug
        uses: rlespinasse/github-slug-action@v2.x

      - name: Build
        run: make build

      - name: Push build cache images
        run: make push-build-cache

      - name: Push
        run: make push
        if: ${{ github.ref == 'refs/heads/master' }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRODUCTION_KEY }}
          known_hosts: ${{ secrets.PRODUCTION_HOST }}
        if: ${{ github.ref == 'refs/heads/master' }}

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.PRODUCTION_HOST }} >> ~/.ssh/known_hosts
        if: ${{ github.ref == 'refs/heads/master' }}

      - name: Deploy
        run: make deploy
        env:
          BUILD_NUMBER: ${GITHUB_RUN_NUMBER}
          HOST: ${{ secrets.PRODUCTION_HOST }}
          PORT: ${{ secrets.PRODUCTION_PORT }}
          DB_ROOT_USER: ${{secrets.DB_ROOT_USER}}
          DB_ROOT_PASSWORD: ${{secrets.DB_ROOT_PASSWORD}}
          DB_API_USER: ${{secrets.DB_API_USER}}
          DB_API_PASSWORD: ${{secrets.DB_API_PASSWORD}}
          MAILER_HOST: ${{secrets.MAILER_HOST}}
          MAILER_PORT: ${{secrets.MAILER_PORT}}
          MAILER_USERNAME: ${{secrets.MAILER_USERNAME}}
          MAILER_PASSWORD: ${{secrets.MAILER_PASSWORD}}
          MAILER_ENCRYPTION: ${{secrets.MAILER_ENCRYPTION}}
          MAILER_FROM_EMAIL: ${{secrets.MAILER_FROM_EMAIL}}
          FB_APP_ID: ${{secrets.FB_APP_ID}}
          FB_APP_SECRET: ${{secrets.FB_APP_SECRET}}
          GOOGLE_APP_ID: ${{secrets.GOOGLE_APP_ID}}
          GOOGLE_APP_SECRET: ${{secrets.GOOGLE_APP_SECRET}}
          FRONTEND_URL: ${{secrets.FRONTEND_URL}}
          JWT_SECRET: ${{secrets.JWT_SECRET}}
        if: ${{ github.ref == 'refs/heads/master' }}
